### ISSUE TITLE
Request for cooperation

### ISSUE THREAD

**Issue by Frans-Willem** [blueluna/psila#1]
Hi Erik,

I noticed you've found my Zigbee/Rust experimentation, and in turn I've stumbled upon your project. It turns out that there's quite a big overlap, and I would like to have a chat to see if we could split off the parts of our projects that we could use together (e.g. mostly the 802.15.4 & Zigbee data structures).
I'm quite fond of your Pack trait (in contrast to my [Serialize/Deserialize traits](https://github.com/Frans-Willem/ZigbeeRustPlayground/blob/fwh/new-attempt2/src/parse_serialize.rs)), and I could port my [automated deriving for basics structs and enums](https://github.com/Frans-Willem/ZigbeeRustPlayground/blob/fwh/new-attempt2/src/parse_serialize.rs#L217) over to that trait.
The point of contention I do see is that you're bound by no-std, while I'd like to enjoy the comforts of std in my hub implementation, so we'd have to figure out a pack function that could either take a pre-allocated &mut [u8] as well as a &mut Vec<u8>, and similarly would have to figure out data-structures that fit both our use-cases.

If you're interested, we could continue the conversation here, or feel free to e-mail me at fw@hardijzer.nl.

Frans-willem

**Comment by blueluna** [comment]
Hello Frans-Willem,

Sorry for the late response. Thank you for your interest in my project. As you have discovered, I found you project some time ago and have had a look. I did not reach out to you since we seemed to have different constraints and goals, but I agree that there probably is quite some overlap between our projects. Unfortunately I am in a period where I do not have much time for this project, and probably won't for the next coming months. But I am happy to answer any questions or comments on improvements that you have. You are welcome to take any code and/or inspiration for my work.

With regards to std and no_std. The `psila_data` and `psila_service` crates should use std if not the `core` feature is used. I have had to cut corners to provide no_std functionality though.

Regards,
Erik

**Comment by Frans-Willem** [comment]
No worries, I'm not always working on the same project either :)
When you have time, see if my definitions of [Pack, PackTagged](https://github.com/Frans-Willem/ZigbeeRustPlayground/blob/f4cb9a319fc344828210d5a4cc0aa340335ea686/src/pack/pack.rs#L24), and [ExtEnum](https://github.com/Frans-Willem/ZigbeeRustPlayground/blob/f4cb9a319fc344828210d5a4cc0aa340335ea686/src/pack/ext_enum.rs#L5) (including [automatic derivation](https://github.com/Frans-Willem/ZigbeeRustPlayground/blob/db1743de31c642e69ecd567f4a4970c6e943f5d9/pack_derive/src/lib.rs#L1)) would be useful to you too. If they are, we can extract them to a separate package ('ieee802154-packing' maybe?) and then possibly work together on the other structures/enums used by Zigbee.

**Comment by blueluna** [comment]
Sure, interesting. I will have a look. For 802.15.4 I am using https://github.com/braun-embedded/rust-ieee802.15.4 which I have contributed a bit to.
